[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dnd2024-character-json"
version = "0.1.0"
dependencies = [
    "pypdf==6.13.2",
    "pymupdf==1.27.2.3",
    "jsonschema==4.26.0",
]

[tool.setuptools]
# Expose the python script modules at the root
py-modules = ["validate", "generate_sheets"]

[tool.setuptools.package-data]
"*" = [
    "spec/**/*",                  # Grabs every file/subfolder inside the spec folder (schema, changelog, examples)
    "_character_sheet_template.pdf"
]